### PR TITLE
Create schema specific to the PR number

### PR DESCRIPTION
**Pull request by leoebfolsom**
This could definitely be refined 😅  but this is the general idea. I attempted to change as little as possible in your current setup.

### CODE REVIEW

**Comment by bruno-szdl** [comment]
Hey @leoebfolsom, what if we use   {{ github.event.pull_request.number }} instead
What do you think?

Even in the repo you called it is written this:

> If the event is a pull_request, it's very easy to get the current PR number from the context via ${{ github.event.number }}, but unfortunately this information does not seem to be readily available for a push event. This action sends a request to GitHub to find the PR associated with the current SHA, and returns its number in the number output. number will be an empty string if there is no PR.

I only see we using this in pull requests, so {{ github.event.pull_request.number }}. Do you see a case where we need to do it with this jwalton/gh-find-current-pr? Not sure I completely understood it

**Comment by bruno-szdl** [comment]
I added {{ github.event.pull_request.number }}  here https://github.com/bruno-szdl/dbt-ci-cd/pull/10 and it is working fine

**Comment by leoebfolsom** [comment]
@bruno-szdl let's do it! I can ask internally why we use the jwalton action, but maybe it is unnecessary and we can update our own script. If I hear of a "good reason" why not to use `{{ github.event.pull_request.number }}`, I'll let you know.

**Comment by bruno-szdl** [comment]
Perfect, let me know if there is a good reason. I will close this PR then, and merge the one with `{{ github.event.pull_request.number }}`

Thanks for agreeing with it!

**Comment by bruno-szdl** [comment]
We will use `{{ github.event.pull_request.number }}` while we don't have a good reason to use jwalton action

**Pull request closed without merging**
